title: Barnefilmer i Verdal og Steinkjer
description: |
  Oppdatert oversikt over barne- og ungdomsfilmer på Verdal kino og Steinkjer kino, med dato, klokkeslett, sal og korte norske filmomtaler.
url: https://shiny.grendel.no/kino-barn-innherred
image: https://shiny.grendel.no/kino-barn-innherred/share.svg
image_type: image/svg+xml
site_name: Grendel
locale: nb_NO
favicon: /kino-barn-innherred/favicon.svg
favicon_png: "/kino-barn-innherred/favicon-32.png"
theme_color: '#176b5f'